### ISSUE TITLE
Silent misbehaviour: bad date formatting

### ISSUE THREAD

**Issue by equwal** [coleslaw-org/coleslaw#172]
If you use a date like `date: 2019-4-28` instead of `date: 2019-04-28`, coleslaw will silently make that date the same as `2019-40-28`.

It would be nice if coleslaw threw an error instead. With [coleslaw-mode](https://spensertruex.com/coleslaw-mode) you can have your date inserted by itself, so I found this on one of my old posts where I interted it manually.

**Comment by PuercoPop** [comment]
Hey, I can't reproduce the issue. If I use 2019-4-28 as the date I get 2019-4-28. parse-metadata doesn't try to massage the data and the [template functions](https://github.com/coleslaw-org/coleslaw/blob/master/themes/hyde/post.tmpl#L16) writes the date as is.

Could you post more specific reproduction instructions?

**Comment by equwal** [comment]
Sure:
Make a coleselaw repo
Make two files
Make one  2019-4-28
Make another have 2019-04-29
Deploy
Look at the index, the 2019-4-28 should be above (more recent) than 2019-04-28.

**Comment by guicho271828** [comment]
So it is not like the date is actually formatted as `2019-40-28` , but merely ordered in a weird manner?

**Comment by equwal** [comment]
Sorry for having been imprecise.

What I mean 

> So it is not like the date is actually formatted as `2019-40-28` , but merely ordered in a weird manner?

Sorry for having been imprecise earlier.

This is what I mean, that in the index pages, when sorted by date, the order of the blog posts is off.

**Comment by equwal** [comment]
I'm no longer convinced this issue is worth the effort to try to fix.
