### ISSUE TITLE
I would start merging the PRs

### ISSUE THREAD

**Issue by guicho271828** [coleslaw-org/coleslaw#176]
I just wanted to let you know not to surprise you.
Thanks

**Comment by guicho271828** [comment]
Oh ok I still can't merge requests.

**Comment by PuercoPop** [comment]
@guicho271828 Just checked and the base permission was read, I've updated it to include write as well. Merge away! Thanks for working on Coleslaw!

**Comment by guicho271828** [comment]
Thank you for the added permission.
I would set some standard for the new feature commits -- they should be documented so that someone can find the feature at least! I will work on the Wiki page for it.

**Comment by kingcons** [comment]
This is awesome work @guicho271828. Glad to have you aboard and looking forward to seeing your CLI tool land. :)

**Comment by guicho271828** [comment]
Do you think it is important to preserve the old branches that are already merged? They kind of look messy.

**Comment by guicho271828** [comment]
There are so far two cli interfaces in the forks.
I checked the cli-command branch by @PuercoPop , are you still maintaining this?

**Comment by PuercoPop** [comment]
> Do you think it is important to preserve the old branches that are already merged? They kind of look messy.

No, if they are _merged_ lets delete them.

> I checked the cli-command branch by @PuercoPop , are you still maintaining this?

I haven't looked into it in ages, feel free to delete it, but lets keep other wip branches.

**Comment by guicho271828** [comment]
sure!

**Comment by guicho271828** [comment]
Travis account for coleslaw-org does not seem to be set up yet. (only for kingcons account)

**Comment by guicho271828** [comment]
clearned up some merged brnaches.

**Comment by svetlyak40wt** [comment]
Should we close this Issue now?
