### ISSUE TITLE
Roswell installation instructions are wrong

### ISSUE THREAD

**Issue by lucaregini** [coleslaw-org/coleslaw#186]
Running "ros install coleslaw" fails because it seems that the quicklisp distribution doesn't contain a roswell script folder resulting in a "roswell scripts not found" failure at the end of the setup.

Please change the documentation so to  indicate "ros install coleslaw-org/coleslaw" as the proper way to install the project using roswell. As an alternative please fix the issue in quicklisp.

**Comment by guicho271828** [comment]
Done!
