### ISSUE TITLE
cl-compile-template dependency no longer maintained -- 8 years

### ISSUE THREAD

**Issue by equwal** [coleslaw-org/coleslaw#203]
It's the one that allows for the templates with `{parameters}` like this.

The last change to compile-template in quicklisp was in **2015.** It doesn't compile due to a couple of accidentally not-to-spec things. They are:
`declaim function &optional` in some files and the way the asdf "modules" are done also breaks.

I managed to get a hacky patch of compile-template working, but as one of the users of coleslaw I'd like to see this dependency go away so coleslaw can have more
 ### longevity.
hashtag longevity

**Comment by equwal** [comment]
@dertuxmalwieder

**Comment by dertuxmalwieder** [comment]
?

**Comment by equwal** [comment]
sorry meant to put that on my pull
