### ISSUE TITLE
Colorize appears to have a beta for Clojure, but the functionality isn't in Coleslaw.

### ISSUE THREAD

**Issue by BorisKourt** [coleslaw-org/coleslaw#91]
I tried:

`````` md
```clojure
and
```clj
``````

With the `md` post type.

(Interim: Scheme syntax looks almost perfect)

**Comment by shukryzablah** [comment]
This is working fine. Can you try surrounding the code block like below:

```clojure
(ns clojure.examples.hello
   (:gen-class))
(defn hello-world []
   (println "Hello World"))
(hello-world)
```

<img width="1792" alt="Screen Shot 2021-02-27 at 5 07 06 PM" src="https://user-images.githubusercontent.com/28762146/109401722-3af44980-791e-11eb-80a3-83b7cfb5be96.png">

**Comment by shukryzablah** [comment]
Note this comment of mine: https://github.com/coleslaw-org/coleslaw/issues/157#issuecomment-787184433

I recommend using `pygments`, it is a more comprehensive tool.

**Comment by BorisKourt** [comment]
Thanks for the reply! Haven't been exploring coleslaw in almost five years. :) Will close this.
